name: Build and Run on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        cache: true
        msystem: mingw64
        install: patch make mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: true
        version: '5.13.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw73'

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure and Build
      run: |
        cd framework
        mkdir build-win
        cd build-win
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --target simulator-cli
        cd build-win
        windeployqt.exe --release simulator-cli.exe
      shell: msys2 {0}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: simulator-cli
        path: framework/build-win/simulator-cli.exe


  build-mac:
    runs-on: macos-latest

    steps:
    - name: Install Dependencies
      run: brew install qt@5

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure and Build
      run: |
        cd framework
        mkdir build-mac
        cd build-mac
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make simulator-cli
        macdeployqt simulator-cli.app

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: simulator-cli
          path: framework/build-mac/simulator-cli.app

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: sudo apt-get install -y cmake protobuf-compiler libprotobuf-dev qtbase5-dev libqt5opengl5-dev g++ libusb-1.0-0-dev libsdl2-dev libqt5svg5-dev libssl-dev

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - name: 'Install linuxdeploy'
      run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-plugin-qt-x86_64.AppImage

    - name: Configure and Build
      run: |
        cd framework
        mkdir build-linux
        cd build-linux
        cmake ..
        make simulator-cli
        cd ..
        ./linuxdeploy-x86_64.AppImage --appdir build-linux/simulator-cli.AppDir --plugin qt --output appimage

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: simulator-cli
          path: framework/build-linux/simulator-cli.AppImage