name: Build and Run on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.13.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw73'

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure and Build
      run: |
        mkdir build-win
        cd build-win
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --target simulator-cli
      shell: msys2 {0}

